### ISSUE TITLE
not uploading

### ISSUE THREAD

**Issue by vexity222** [efenatuyo/xool#8]
will not upload clothing, only downloads, here is the error for the upload

and my cookie is valid 

ERROR: Traceback (most recent call last):
  File "C:\Users\cotta\Desktop\xool-main\main.py", line 26, in upload
    item_uploaded = src.upload.create_asset(item["name"], path, "shirt" if current_type == "classicshirts" else "pants", cookie, group_id, self.config["description"], 5, 5)
  File "C:\Users\cotta\Desktop\xool-main\src\upload\__init__.py", line 30, in create_asset
    data = requests.get(f"https://apis.roblox.com/assets/user-auth/v1/operations/{dd['operationId']}", headers={'X-CSRF-TOKEN': cookie.x_token()}, cookies={".ROBLOSECURITY": cookie.cookie})
KeyError: 'operationId'

**Comment by efenatuyo** [comment]
Insufficient permission to the group

**Comment by vexity222** [comment]
its an issue with the api, the cookie has sufficient permissions for the group

**Comment by efenatuyo** [comment]
Pretty sure everyone that had this kind of problem didn’t set up the group or the permissions up right

**Comment by vexity222** [comment]
i used this bot perfectly before the api update, and after the fix it broke

**Comment by vexity222** [comment]
help???

**Comment by efenatuyo** [comment]
try it now

**Comment by vexity222** [comment]
still doesnt work

**Comment by vexity222** [comment]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\xool-main1\main.py", line 53, in <module>
    xool(json.loads(open("config.json", "r").read()))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 34 (char 73)

this is the error now

**Comment by vexity222** [comment]
fixed it myself, thanks anyways

**Comment by efenatuyo** [comment]
just saw this issue. if you ever get errors like that it a issue on your config (you filling it out not in the right format)
